### PR TITLE
Install with podman

### LINKED ISSUE #437: [NEW] Support podman engine for installation method
# Description
Supporting Podman engine for installation

# Benefits
As Fedora based distributions comes pre-installed with podman, it would be easier for the developers on these platforms to install SigLens. Also Podman and Podman desktop project is now gaining a lot of traction these days as a good open source alternative to Docker Desktop

# (Optional) Possible Implementation
If you have any ideas on how this should be implemented, let us know here.

# (Optional) Additional Context
Currently on Fedora 39 and getting below error if I use the docker install method - 
```

➜  curl -L https://siglens.com/install.sh | sh                                                                                                 (current-context is not set)

----------Setting up docker----------
sudo: apt-get: command not found
sudo: apt-get: command not found
sudo: apt-key: command not found
curl: (22) The requested URL returned error: 404
main: line 143: lsb_release: command not found
sudo: add-apt-repository: command not found
sudo: apt-get: command not found
Installing docker
sudo: apt-get: command not found
{
  "success": false,
  "message": "malformed JSON",
  "code": "invalid_request"
}install_docker: Docker installation failed during apt-get install on linux
```

### PR DESCRIPTION
**Pull request by Macbeth98**
# Description
- Install Siglens with Podman.

Fixes #437  (link all the GitHub issues this addresses)

# Testing
- I have tested the install script by running against the AWS EC2 instance.

# Checklist:

- [X] I have self-reviewed this PR.
- [X] I have removed all print-debugging and commented-out code that should not be merged.
- [X] I have added sufficient comments in my code, particularly in hard-to-understand areas.
- [X] I have formatted the code, if applicable. For Go, I have run `goimports -w .`.

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -0,0 +1,570 @@
...
+echo "===> Selected container tool: $CONTAINER_TOOL"
+
+
+# Extract the version number from pkg/config/version.go by getting everything
+# inside the quotes. Use -n to supress printing each line, and p to print the
+# modified line.
+SIGLENS_VERSION=`\
+    curl  --silent "https://api.github.com/repos/siglens/siglens/releases/latest" |
+    grep '"tag_name":' |
+    sed -E 's/.*"([^"]+)".*/\1/'`
```
Comment (AndrewHess) [inline install.sh:29]: nit: this comment seems incorrect (it looks like this is the same comment from install_with_docker.sh, which is also incorrect)

File: install.sh [hunk 2]
```diff
@@ -0,0 +1,570 @@
...
+   Darwin*)
+     os="darwin"
+     package_manager="brew" ;;
+   Linux*amzn2*)
+     os="amazon linux"
+     package_manager="yum" ;;
+   Red\ Hat*|CentOS*|Fedora*)
+     os="linux"
+     package_manager="yum" ;;
+   Ubuntu*|Pop!_OS|Debian*|Linux*|Mint*)
```
Comment (AndrewHess) [inline install.sh:59]: Should `Linux*|Mint*` be `Linux\ Mint*`, or should it be what you have? (I'm just looking at the diff with install_with_docker.sh)

**Review by AndrewHess — COMMENTED** [review]
This looks really good. I think you can remove the install_with_podman.sh file since all of that logic is now in the install.sh script. But don't delete the install_with_docker.sh file yet because that's still referenced by the website: https://github.com/siglens/siglens.github.io/blob/develop/install.sh

File: install.sh (hunk 2 above)
Comment (Macbeth98) [reply install.sh:59]: I changed this to how it is in the docker script. It is now changed to `Ubuntu*|Pop!_OS|Debian*|Linux*|Linux\ Mint*` But I do feel `Linux* | Linux\ Mint*` is redundant since `Linux*` covers the other Mint distributions also and we are assigning os as linux and package manager to `apt-get` 

So should I remove `Linux\ Mint*`?

Comment (AndrewHess) [reply install.sh:59]: Oh I see, yeah as long as having `Linux*` does not include things we don't want included, you can just have `Linux*` and remove `Linux\ Mint*`

Comment (Macbeth98) [reply install.sh]: @AndrewHess ignore the above comment.

File: install.sh [hunk 3]
```diff
@@ -46,6 +47,36 @@ is_command_present() {
...
+    dist_version=$(lsb_release -rs)
+elif  [ -f /etc/os-release ]; then
+    . /etc/os-release
+    dist_id=$NAME
+    dist_version=$VERSION_ID
+elif is_command_present distro; then
+    dist_id=$(distro | awk '{print $1}')
+    dist_version=$(distro | awk '{print $2}')
+else 
+    echo "Couldn't determine the OS distribution"
```
Comment (AndrewHess) [inline install.sh:65]: I'm getting this message on mac, but then installation (with docker) works. Is this just for linux flavors?

**Review by AndrewHess — COMMENTED** [review]
This looks great. When I try to run the install script, first I have to run `chmod +x install.sh` and then it works, but `git diff` shows the mode change. Are you able to change the mode and push that change?

File: install.sh (hunk 3 above)
Comment (Macbeth98) [reply install.sh:65]: Yes, that is just for Linux flavors. I am using the  dist_id which is usually `ubuntu, rhel, fedora, centos`, etc, to download the appropriate docker repo.

**Comment by Macbeth98** [comment]
> This looks great. When I try to run the install script, first I have to run `chmod +x install.sh` and then it works, but `git diff` shows the mode change. Are you able to change the mode and push that change?

I have changed the mode and pushed it. Let me know of any further changes. Thank you!

**Review by AndrewHess — APPROVED** [review]
