### PR TITLE
Visualization Tab - Display Bar Graph for Stats Query on Logs Screen & Errors related to Log-Screens

### LINKED ISSUE #1045: [STORY] Visualization Tab - Display Bar Graph for Stats Query on Logs Screen
# Description
When running a stats query on the logs screen within the visualization tab, the expected outcome is to display the results in a bar graph format similar to what we show on dashboards when we run a stats query and choose chart type bar chart.

# Steps to Reproduce
1. Navigate to the logs screen.
2. Open the visualization tab.
3. Run a stats query. Ex- `batch="batch-1" | stats avg(latency) BY city` 

# Expected Behavior
The stats query results should be displayed as a bar graph within the visualization tab.

### PR DESCRIPTION
**Pull request by Divyanshu11011**
# Description
1) Added Bar Graph for Stats Query on Logs Screen.
2) Support multilple Stats Query .
3) Supports Multiple Group By Values.
4) Different Timestamps for timestamp / category data
5) Fixed error related to logs screen and Chart Not Displaying for First Query until Refreshed
6) Graph Auto-Adjusts As Per Mangnitude
7) Made the chart responsive

Fixes #1045 #646 

# Snapshots

https://github.com/user-attachments/assets/f091c53c-bf12-46c4-9a01-285028eb5f73

image

Multiple Group-By

Before marking your pull request as ready for review, complete the following.

- [x] I have self-reviewed this PR.
- [x] I have removed all print-debugging and commented-out code that should not be merged.
- [x] I have added sufficient comments in my code, particularly in hard-to-understand areas.
- [x] I have formatted the code, if applicable. For Go, I have run `goimports -w .`.

### CODE REVIEW

**Comment by AndrewHess** [comment]
I think it would be good to sort the x-axis values. I tested with
```
* | stats count by weekday, group
```
and the bars seem to be in a random order.

However, the normal `Table` tab also has them in what looks like a random order, so maybe sorting them belongs in a different PR that would do it for both the `Table` and `Visualization` tabs. What do you think @sonamgupta21 @Divyanshu11011 ?

File: static/js/search.js [hunk 1]
```diff
@@ -941,17 +942,27 @@ function parseInterval(interval) {
 }
 
 function timeChart() {
-    if (isTimechart) {
```
Comment (sonamgupta21) [inline static/js/search.js:944]: If I run a query that supports a bar graph and then run another query that does not, the chart should go away and show the prompt `This query doesn't support visualization.`

Don't remove this code, we already have a condition check for the time chart query, so you can add the logic to check if it is an aggregation query.

**Review by sonamgupta21 — APPROVED** [review]
